"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { DEMO_GOALS } from "@/lib/demo-data";
import {
  Target, Calendar, AlertTriangle, CheckCircle2, Circle, Plus, Trash2,
  Brain, ArrowRight, Activity, TrendingUp, Sparkles, Loader2
} from "lucide-react";
import toast from "react-hot-toast";

interface Goal {
  id: string;
  title: string;
  category: string;
  deadline: Date;
  priority: string;
  status: string;
  successProbability: number;
  alertLevel: string;
  progress: number;
  milestones: { title: string; completed: boolean }[];
  keyFocusAreas?: string[];
  riskFactors?: string[];
}

export default function GoalsPage() {
  const [goals, setGoals] = useState<Goal[]>(
    DEMO_GOALS.map((g) => ({
      ...g,
      keyFocusAreas: g.id === "goal-001" ? ["Integration & Differential Equations", "Chemistry mock tests", "Physics revision"] : ["Core mastery", "Time management"],
      riskFactors: g.id === "goal-001" ? ["Syllabus completion lag", "Lack of mock test practice"] : ["Burnout"]
    }))
  );

  const [activeGoalId, setActiveGoalId] = useState<string | null>(goals[0]?.id || null);
  const [isCreating, setIsCreating] = useState(false);
  const [loading, setLoading] = useState(false);

  // New goal form state
  const [newGoalTitle, setNewGoalTitle] = useState("");
  const [newGoalCategory, setNewGoalCategory] = useState("exam");
  const [newGoalPriority, setNewGoalPriority] = useState("high");
  const [newGoalDeadline, setNewGoalDeadline] = useState("");

  const activeGoal = goals.find((g) => g.id === activeGoalId) || goals[0];

  const handleCreateGoal = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newGoalTitle.trim() || !newGoalDeadline) {
      toast.error("Please fill in all fields");
      return;
    }

    setLoading(true);
    try {
      const response = await fetch("/api/agents/goal-planner", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          goal: newGoalTitle,
          deadline: newGoalDeadline,
          role: "student",
        }),
      });

      if (!response.ok) throw new Error("Agent failed");

      const data = await response.json();

      const newGoal: Goal = {
        id: `goal-${Date.now()}`,
        title: newGoalTitle,
        category: newGoalCategory,
        deadline: new Date(newGoalDeadline),
        priority: newGoalPriority,
        status: "active",
        successProbability: data.successProbability || 75,
        alertLevel: data.successProbability > 80 ? "green" : data.successProbability > 60 ? "yellow" : "red",
        progress: 0,
        milestones: (data.milestones || []).map((m: any) => ({
          title: m.title,
          completed: false,
        })),
        keyFocusAreas: data.keyFocusAreas || [],
        riskFactors: data.riskFactors || [],
      };

      setGoals((prev) => [newGoal, ...prev]);
      setActiveGoalId(newGoal.id);
      setIsCreating(false);
      // Reset form
      setNewGoalTitle("");
      setNewGoalDeadline("");
      toast.success("Goal generated by AI Goal Planning Agent! 🎯");
    } catch (error) {
      console.error(error);
      // Create fallback goal
      const fallbackGoal: Goal = {
        id: `goal-${Date.now()}`,
        title: newGoalTitle,
        category: newGoalCategory,
        deadline: new Date(newGoalDeadline),
        priority: newGoalPriority,
        status: "active",
        successProbability: 80,
        alertLevel: "green",
        progress: 0,
        milestones: [
          { title: "Understand Core Concepts", completed: false },
          { title: "Practice Problem Sets", completed: false },
          { title: "Mid-term review & mocks", completed: false },
          { title: "Final revision & Exam Day", completed: false },
        ],
        keyFocusAreas: ["Time allocation", "Daily practice", "Mock review"],
        riskFactors: ["Procrastination"],
      };
      setGoals((prev) => [fallbackGoal, ...prev]);
      setActiveGoalId(fallbackGoal.id);
      setIsCreating(false);
      setNewGoalTitle("");
      setNewGoalDeadline("");
      toast.success("Goal created with AI-fallback template!");
    } finally {
      setLoading(false);
    }
  };

  const toggleMilestone = (goalId: string, index: number) => {
    setGoals((prev) =>
      prev.map((g) => {
        if (g.id === goalId) {
          const updatedMilestones = [...g.milestones];
          updatedMilestones[index].completed = !updatedMilestones[index].completed;
          const completedCount = updatedMilestones.filter((m) => m.completed).length;
          const progress = Math.round((completedCount / updatedMilestones.length) * 100);

          // Update alert level & success probability dynamically based on progress
          const probModifier = progress - g.progress;
          const newProb = Math.min(100, Math.max(10, g.successProbability + probModifier));
          let newAlert = "green";
          if (newProb < 50) newAlert = "red";
          else if (newProb < 75) newAlert = "yellow";

          return {
            ...g,
            milestones: updatedMilestones,
            progress,
            successProbability: newProb,
            alertLevel: newAlert,
          };
        }
        return g;
      })
    );
  };

  const handleDeleteGoal = (goalId: string) => {
    if (goals.length <= 1) {
      toast.error("You must keep at least one goal!");
      return;
    }
    const updated = goals.filter((g) => g.id !== goalId);
    setGoals(updated);
    if (activeGoalId === goalId) {
      setActiveGoalId(updated[0].id);
    }
    toast.success("Goal deleted.");
  };

  const alertColors: Record<string, string> = {
    green: "#10b981",
    yellow: "#f59e0b",
    red: "#ef4444",
    black: "#7c15f0",
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-display font-bold text-white flex items-center gap-2">
            <Target className="text-violet-400" />
            Goals & Milestones
          </h1>
          <p className="text-slate-500 text-xs mt-0.5">
            Create, track, and decompose your ambitions using our Gemini Goal Planning Agent.
          </p>
        </div>
        <button
          onClick={() => setIsCreating(true)}
          className="btn-primary py-2.5 px-4 text-xs font-semibold"
        >
          <Plus size={16} />
          Create New Goal
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left column: Goal list */}
        <div className="space-y-3">
          <div className="text-slate-400 text-xs font-semibold uppercase tracking-wider px-1">Active Ambitions</div>
          {goals.map((goal) => {
            const color = alertColors[goal.alertLevel] || "#7c15f0";
            const isActive = goal.id === activeGoalId;
            return (
              <div
                key={goal.id}
                onClick={() => setActiveGoalId(goal.id)}
                className={`card-base p-4 cursor-pointer transition-all duration-300 relative overflow-hidden group ${
                  isActive ? "border-violet-500/50 bg-white/[0.04]" : "hover:bg-white/[0.02]"
                }`}
              >
                <div className="absolute top-0 right-0 h-1 w-20" style={{ background: color }} />
                <div className="flex justify-between items-start mb-2">
                  <span className="text-white text-sm font-semibold truncate max-w-[80%]">
                    {goal.title}
                  </span>
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      handleDeleteGoal(goal.id);
                    }}
                    className="opacity-0 group-hover:opacity-100 p-1 rounded hover:bg-red-500/20 text-red-400 transition-all"
                  >
                    <Trash2 size={12} />
                  </button>
                </div>
                <div className="flex justify-between items-center text-[10px] text-slate-500 mb-3">
                  <span className="flex items-center gap-1">
                    <Calendar size={10} />
                    {new Date(goal.deadline).toLocaleDateString("en-IN", { month: "short", year: "numeric" })}
                  </span>
                  <span className="capitalize font-medium" style={{ color }}>{goal.priority} priority</span>
                </div>

                {/* Progress bar */}
                <div className="flex items-center gap-2">
                  <div className="progress-track flex-1">
                    <div className="progress-fill" style={{ width: `${goal.progress}%`, background: color }} />
                  </div>
                  <span className="text-[10px] font-mono text-slate-400">{goal.progress}%</span>
                </div>
              </div>
            );
          })}
        </div>

        {/* Right columns: Goal Details */}
        <div className="lg:col-span-2 space-y-6">
          {activeGoal ? (
            <motion.div
              key={activeGoal.id}
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              className="space-y-6"
            >
              {/* Goal Title & Status Card */}
              <div className="card-base p-6 relative overflow-hidden">
                <div
                  className="absolute inset-y-0 left-0 w-1.5"
                  style={{ background: alertColors[activeGoal.alertLevel] }}
                />
                <div className="flex justify-between items-start gap-4">
                  <div>
                    <span className="text-[10px] uppercase font-bold tracking-wider px-2 py-0.5 rounded bg-white/5 text-slate-400">
                      {activeGoal.category} goal
                    </span>
                    <h2 className="text-xl font-display font-bold text-white mt-2">{activeGoal.title}</h2>
                    <p className="text-slate-400 text-xs mt-1 flex items-center gap-1.5">
                      <Calendar size={12} className="text-violet-400" />
                      Target Date: {new Date(activeGoal.deadline).toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}
                    </p>
                  </div>
                  <div className="text-right">
                    <div className="text-slate-400 text-[10px] font-semibold">Success Probability</div>
                    <div
                      className="text-3xl font-display font-bold font-mono mt-1"
                      style={{ color: alertColors[activeGoal.alertLevel] }}
                    >
                      {activeGoal.successProbability}%
                    </div>
                    <span
                      className="text-[9px] px-2 py-0.5 rounded font-bold inline-block mt-1 uppercase"
                      style={{
                        background: `${alertColors[activeGoal.alertLevel]}15`,
                        color: alertColors[activeGoal.alertLevel]
                      }}
                    >
                      {activeGoal.alertLevel} alert level
                    </span>
                  </div>
                </div>
              </div>

              {/* Milestones list */}
              <div className="card-base p-6">
                <h3 className="text-sm font-semibold text-white mb-4 flex items-center gap-2">
                  <Activity size={16} className="text-violet-400" />
                  Structured Milestones
                </h3>
                <div className="space-y-3">
                  {activeGoal.milestones.map((milestone, idx) => (
                    <div
                      key={idx}
                      onClick={() => toggleMilestone(activeGoal.id, idx)}
                      className={`flex items-start gap-3 p-3.5 rounded-xl cursor-pointer transition-all ${
                        milestone.completed ? "bg-emerald-500/5 border border-emerald-500/20 opacity-70" : "glass hover:bg-white/5 border border-white/5"
                      }`}
                    >
                      <div className="mt-0.5 flex-shrink-0">
                        {milestone.completed ? (
                          <CheckCircle2 size={16} className="text-emerald-400" />
                        ) : (
                          <Circle size={16} className="text-slate-600 hover:text-white transition-colors" />
                        )}
                      </div>
                      <div>
                        <div
                          className={`text-sm font-medium ${
                            milestone.completed ? "line-through text-slate-500" : "text-white"
                          }`}
                        >
                          {milestone.title}
                        </div>
                        <div className="text-[10px] text-slate-500 mt-1">
                          Phase Milestone {idx + 1}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* AI Agent Console Insights */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="glass-violet rounded-2xl p-5">
                  <h4 className="text-xs font-semibold text-violet-400 flex items-center gap-2 mb-3">
                    <Brain size={14} />
                    AI Key Focus Areas
                  </h4>
                  <ul className="space-y-2">
                    {activeGoal.keyFocusAreas?.map((item, idx) => (
                      <li key={idx} className="text-xs text-slate-300 flex items-center gap-2">
                        <Sparkles size={10} className="text-violet-400" />
                        {item}
                      </li>
                    ))}
                  </ul>
                </div>
                <div className="glass-yellow rounded-2xl p-5">
                  <h4 className="text-xs font-semibold text-yellow-500 flex items-center gap-2 mb-3">
                    <AlertTriangle size={14} />
                    Risk Prediction Factors
                  </h4>
                  <ul className="space-y-2">
                    {activeGoal.riskFactors?.map((item, idx) => (
                      <li key={idx} className="text-xs text-slate-300 flex items-center gap-2">
                        <span className="w-1 h-1 rounded-full bg-yellow-400" />
                        {item}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </motion.div>
          ) : (
            <div className="card-base p-12 text-center text-slate-500">
              Select or create a goal to review milestone details
            </div>
          )}
        </div>
      </div>

      {/* Create Goal Modal */}
      <AnimatePresence>
        {isCreating && (
          <div className="fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4 backdrop-blur-sm">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="card-base p-6 max-w-md w-full relative"
            >
              <h3 className="font-display font-bold text-lg text-white mb-1">Create Goal with AI Architect</h3>
              <p className="text-slate-500 text-xs mb-5">
                Our Gemini Goal Planning Agent will analyze your target and break it into automated milestones.
              </p>

              <form onSubmit={handleCreateGoal} className="space-y-4">
                <div>
                  <label className="text-slate-400 text-xs font-semibold block mb-1">Goal Ambition</label>
                  <input
                    type="text"
                    required
                    placeholder="e.g. Master React and Node.js to build a SaaS"
                    className="input-field"
                    value={newGoalTitle}
                    onChange={(e) => setNewGoalTitle(e.target.value)}
                  />
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="text-slate-400 text-xs font-semibold block mb-1">Category</label>
                    <select
                      className="input-field py-2"
                      value={newGoalCategory}
                      onChange={(e) => setNewGoalCategory(e.target.value)}
                    >
                      <option value="exam">Exam</option>
                      <option value="career">Career</option>
                      <option value="skill">Skill</option>
                      <option value="project">Project</option>
                      <option value="fitness">Fitness</option>
                    </select>
                  </div>
                  <div>
                    <label className="text-slate-400 text-xs font-semibold block mb-1">Priority</label>
                    <select
                      className="input-field py-2"
                      value={newGoalPriority}
                      onChange={(e) => setNewGoalPriority(e.target.value)}
                    >
                      <option value="critical">🔴 Critical</option>
                      <option value="high">🟡 High</option>
                      <option value="medium">🔵 Medium</option>
                      <option value="low">🟢 Low</option>
                    </select>
                  </div>
                </div>

                <div>
                  <label className="text-slate-400 text-xs font-semibold block mb-1">Deadline Date</label>
                  <input
                    type="date"
                    required
                    className="input-field"
                    value={newGoalDeadline}
                    onChange={(e) => setNewGoalDeadline(e.target.value)}
                  />
                </div>

                <div className="flex gap-3 justify-end pt-4 border-t border-white/5">
                  <button
                    type="button"
                    onClick={() => setIsCreating(false)}
                    className="px-4 py-2 text-xs font-semibold text-slate-400 hover:text-white"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    disabled={loading}
                    className="btn-primary py-2 px-5 text-xs font-semibold flex items-center gap-1.5"
                  >
                    {loading ? (
                      <>
                        <Loader2 size={12} className="animate-spin" />
                        Generating roadmaps...
                      </>
                    ) : (
                      <>
                        <Brain size={12} />
                        Run Agent Plan
                      </>
                    )}
                  </button>
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
