"use client";

import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { DEMO_USER, DEMO_GOALS, DEMO_TASKS, DEMO_NOTIFICATIONS, DEMO_AGENTS, DEMO_WEEKLY_PROGRESS } from "@/lib/demo-data";
import { CheckCircle2, Circle, Clock, TrendingUp, Zap, Brain, Target, AlertTriangle, Activity } from "lucide-react";
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  RadialBarChart, RadialBar, PieChart, Pie, Cell
} from "recharts";

function AIBriefingCard() {
  const [typing, setTyping] = useState(true);
  const briefing = `Good morning, Arjun! 🌅 Today is critical — you have 4 high-priority tasks. Your JEE Mathematics syllabus is 3 weeks behind. The Risk Prediction Agent recommends spending 3h on Integration today. Your success probability is 72% — let's push it to 80% this week! You're on a 14-day streak. Don't break it! 💪`;
  const [displayed, setDisplayed] = useState("");

  useEffect(() => {
    let i = 0;
    const timer = setInterval(() => {
      if (i < briefing.length) {
        setDisplayed(briefing.slice(0, i + 1));
        i++;
      } else {
        setTyping(false);
        clearInterval(timer);
      }
    }, 18);
    return () => clearInterval(timer);
  }, []);

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="col-span-full glass-violet rounded-2xl p-6"
    >
      <div className="flex items-center gap-3 mb-4">
        <div className="w-9 h-9 rounded-xl flex items-center justify-center agent-active"
          style={{ background: "linear-gradient(135deg, #7c15f0, #a855f7)" }}>
          <Brain size={18} className="text-white" />
        </div>
        <div>
          <div className="font-display font-bold text-white text-sm">AI Morning Briefing</div>
          <div className="text-slate-500 text-xs">Generated by Gemini 2.5 Pro · just now</div>
        </div>
        <div className="ml-auto badge-violet text-xs">
          <Zap size={10} className="animate-pulse" />
          Live
        </div>
      </div>
      <p className="text-slate-300 text-sm leading-relaxed">
        {displayed}
        {typing && <span className="inline-block w-0.5 h-4 bg-violet-400 animate-pulse ml-0.5 align-middle" />}
      </p>
    </motion.div>
  );
}

function SuccessScoreGauge() {
  const score = DEMO_USER.successScore;
  const data = [{ name: "Score", value: score, fill: "#7c15f0" }];

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.9 }}
      animate={{ opacity: 1, scale: 1 }}
      transition={{ delay: 0.1 }}
      className="card-base flex flex-col items-center justify-center text-center"
    >
      <div className="text-slate-400 text-xs font-semibold uppercase tracking-widest mb-2">Success Score</div>
      <div className="relative w-32 h-32">
        <RadialBarChart
          width={128} height={128}
          innerRadius={45} outerRadius={60}
          data={data}
          startAngle={210} endAngle={-30}
        >
          <RadialBar background={{ fill: "rgba(255,255,255,0.05)" }} dataKey="value" cornerRadius={8} />
        </RadialBarChart>
        <div className="absolute inset-0 flex items-center justify-center flex-col">
          <span className="text-3xl font-display font-bold gradient-text">{score}</span>
          <span className="text-slate-500 text-xs">/100</span>
        </div>
      </div>
      <div className="badge-yellow mt-2">⚠️ Yellow Alert</div>
      <div className="text-slate-500 text-xs mt-2">🔥 {DEMO_USER.streak} day streak</div>
    </motion.div>
  );
}

function QuickStats() {
  const stats = [
    { label: "Goals Active", value: DEMO_GOALS.length, icon: <Target size={16} />, color: "#7c15f0" },
    { label: "Tasks Today", value: DEMO_TASKS.length, icon: <CheckCircle2 size={16} />, color: "#06b6d4" },
    { label: "Hours Invested", value: "6.5h", icon: <Clock size={16} />, color: "#10b981" },
    { label: "Completion", value: "68%", icon: <TrendingUp size={16} />, color: "#f59e0b" },
  ];

  return (
    <>
      {stats.map((s, i) => (
        <motion.div
          key={i}
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 + i * 0.05 }}
          className="card-base flex items-center gap-4"
        >
          <div className="w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0"
            style={{ background: `${s.color}20`, color: s.color }}>
            {s.icon}
          </div>
          <div>
            <div className="text-2xl font-display font-bold text-white">{s.value}</div>
            <div className="text-slate-500 text-xs">{s.label}</div>
          </div>
        </motion.div>
      ))}
    </>
  );
}

function TodaysTasks() {
  const [tasks, setTasks] = useState(DEMO_TASKS);

  const toggle = (id: string) => {
    setTasks((ts) => ts.map((t) =>
      t.id === id ? { ...t, status: t.status === "completed" ? "pending" : "completed" } : t
    ));
  };

  const priorityColor: Record<string, string> = {
    critical: "#ef4444", high: "#f59e0b", medium: "#06b6d4", low: "#10b981"
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.2 }}
      className="card-base col-span-1 md:col-span-2"
    >
      <div className="flex items-center justify-between mb-5">
        <h2 className="font-display font-bold text-white">Today&apos;s Tasks</h2>
        <span className="text-slate-500 text-xs">{tasks.filter(t => t.status === "completed").length}/{tasks.length} done</span>
      </div>

      {/* Progress bar */}
      <div className="progress-track mb-4">
        <div className="progress-fill transition-all duration-500"
          style={{ width: `${(tasks.filter(t => t.status === "completed").length / tasks.length) * 100}%` }} />
      </div>

      <div className="flex flex-col gap-3">
        {tasks.map((task) => (
          <div
            key={task.id}
            onClick={() => toggle(task.id)}
            className={`flex items-start gap-3 p-3 rounded-xl cursor-pointer transition-all duration-200 ${
              task.status === "completed" ? "opacity-50" : "hover:bg-white/5"
            }`}
          >
            <div className="mt-0.5 flex-shrink-0">
              {task.status === "completed"
                ? <CheckCircle2 size={18} className="text-emerald-400" />
                : task.status === "in-progress"
                  ? <div className="w-4.5 h-4.5 w-[18px] h-[18px] rounded-full border-2 border-violet-400 border-t-transparent animate-spin" />
                  : <Circle size={18} className="text-slate-600" />
              }
            </div>
            <div className="flex-1 min-w-0">
              <div className={`text-sm font-medium ${task.status === "completed" ? "line-through text-slate-500" : "text-white"}`}>
                {task.title}
              </div>
              <div className="flex items-center gap-2 mt-1">
                <span className="text-[10px] px-2 py-0.5 rounded-full font-semibold"
                  style={{ background: `${priorityColor[task.priority]}15`, color: priorityColor[task.priority] }}>
                  {task.priority}
                </span>
                <span className="text-slate-600 text-[10px]">⏱ {task.duration}min</span>
                <span className="text-slate-600 text-[10px]">{task.category}</span>
              </div>
            </div>
          </div>
        ))}
      </div>
    </motion.div>
  );
}

function GoalCards() {
  const alertColors: Record<string, string> = {
    green: "#10b981", yellow: "#f59e0b", red: "#ef4444", black: "#6b7280"
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.3 }}
      className="card-base"
    >
      <div className="flex items-center justify-between mb-5">
        <h2 className="font-display font-bold text-white">Active Goals</h2>
        <a href="/dashboard/goals" className="text-violet-400 text-xs hover:text-violet-300">View all →</a>
      </div>

      <div className="flex flex-col gap-4">
        {DEMO_GOALS.map((goal) => {
          const color = alertColors[goal.alertLevel];
          return (
            <div key={goal.id} className="glass rounded-xl p-4">
              <div className="flex items-start justify-between mb-3">
                <div className="flex-1 min-w-0">
                  <div className="text-white text-sm font-semibold truncate">{goal.title}</div>
                  <div className="text-slate-500 text-xs mt-0.5">
                    Deadline: {new Date(goal.deadline).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}
                  </div>
                </div>
                <div className="flex-shrink-0 ml-2">
                  <div className="text-sm font-bold font-mono" style={{ color }}>
                    {goal.successProbability}%
                  </div>
                </div>
              </div>

              {/* Progress */}
              <div className="flex items-center gap-2">
                <div className="progress-track flex-1">
                  <motion.div
                    className="h-full rounded-full"
                    style={{ background: color }}
                    initial={{ width: 0 }}
                    animate={{ width: `${goal.progress}%` }}
                    transition={{ duration: 1, delay: 0.5 }}
                  />
                </div>
                <span className="text-xs font-mono text-slate-400">{goal.progress}%</span>
              </div>

              <div className="flex items-center justify-between mt-2">
                <div className="flex gap-1">
                  {goal.milestones.map((m, i) => (
                    <div key={i} className={`w-2 h-2 rounded-full ${m.completed ? "bg-emerald-400" : "bg-slate-700"}`} />
                  ))}
                </div>
                <span className="text-[10px] px-2 py-0.5 rounded-full font-bold"
                  style={{ background: `${color}15`, color }}>
                  {goal.alertLevel.toUpperCase()} ALERT
                </span>
              </div>
            </div>
          );
        })}
      </div>
    </motion.div>
  );
}

function WeeklyChart() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.3 }}
      className="card-base col-span-1 md:col-span-2"
    >
      <div className="flex items-center justify-between mb-5">
        <h2 className="font-display font-bold text-white">Weekly Progress</h2>
        <span className="badge-cyan text-xs">This Week</span>
      </div>
      <ResponsiveContainer width="100%" height={180}>
        <BarChart data={DEMO_WEEKLY_PROGRESS} barGap={4}>
          <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" />
          <XAxis dataKey="day" tick={{ fill: "#64748b", fontSize: 11 }} axisLine={false} tickLine={false} />
          <YAxis tick={{ fill: "#64748b", fontSize: 11 }} axisLine={false} tickLine={false} />
          <Tooltip
            contentStyle={{ background: "rgba(10,22,40,0.95)", border: "1px solid rgba(124,21,240,0.3)", borderRadius: "12px", color: "#f8fafc" }}
            cursor={{ fill: "rgba(124,21,240,0.08)" }}
          />
          <Bar dataKey="planned" fill="rgba(124,21,240,0.3)" radius={[4, 4, 0, 0]} name="Planned" />
          <Bar dataKey="actual" fill="#7c15f0" radius={[4, 4, 0, 0]} name="Actual" />
        </BarChart>
      </ResponsiveContainer>
    </motion.div>
  );
}

function AgentActivityLog() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.4 }}
      className="card-base"
    >
      <div className="flex items-center justify-between mb-5">
        <h2 className="font-display font-bold text-white flex items-center gap-2">
          <Activity size={16} className="text-violet-400" />
          Agent Activity
        </h2>
        <span className="badge-violet text-xs">
          <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
          Live
        </span>
      </div>

      <div className="flex flex-col gap-3">
        {DEMO_AGENTS.map((agent) => (
          <div key={agent.id} className="flex items-center gap-3 p-2.5 rounded-xl hover:bg-white/5 transition-colors">
            <div className="text-xl flex-shrink-0">{agent.icon}</div>
            <div className="flex-1 min-w-0">
              <div className="text-white text-xs font-semibold truncate">{agent.name}</div>
              <div className="text-slate-500 text-[10px] truncate">{agent.lastAction}</div>
            </div>
            <div className="flex flex-col items-end gap-1">
              <div className={`w-1.5 h-1.5 rounded-full flex-shrink-0 ${agent.status === "active" ? "bg-emerald-400 animate-pulse" : "bg-slate-600"}`} />
              <div className="text-[10px] text-slate-600">{agent.actionTime}</div>
            </div>
          </div>
        ))}
      </div>
    </motion.div>
  );
}

function NotificationsWidget() {
  const unread = DEMO_NOTIFICATIONS.filter((n) => !n.read);
  const alertBg: Record<string, string> = {
    green: "rgba(16,185,129,0.1)", yellow: "rgba(245,158,11,0.1)",
    red: "rgba(239,68,68,0.1)", black: "rgba(55,65,81,0.3)"
  };
  const alertText: Record<string, string> = {
    green: "#34d399", yellow: "#fbbf24", red: "#f87171", black: "#9ca3af"
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.4 }}
      className="card-base"
    >
      <div className="flex items-center justify-between mb-5">
        <h2 className="font-display font-bold text-white">Notifications</h2>
        <span className="w-5 h-5 rounded-full bg-red-500 text-white text-[10px] font-bold flex items-center justify-center">
          {unread.length}
        </span>
      </div>

      <div className="flex flex-col gap-2">
        {DEMO_NOTIFICATIONS.slice(0, 4).map((notif) => (
          <div key={notif.id} className="p-3 rounded-xl flex items-start gap-3 transition-all"
            style={{ background: alertBg[notif.alertLevel] }}>
            <div className="text-base flex-shrink-0">{notif.title.split(" ")[0]}</div>
            <div className="flex-1 min-w-0">
              <div className="text-white text-xs font-semibold truncate">{notif.title.slice(3)}</div>
              <div className="text-slate-500 text-[10px] leading-relaxed line-clamp-2 mt-0.5">{notif.body}</div>
            </div>
            {!notif.read && (
              <div className="w-2 h-2 rounded-full mt-1 flex-shrink-0" style={{ background: alertText[notif.alertLevel] }} />
            )}
          </div>
        ))}
      </div>
    </motion.div>
  );
}

export default function DashboardPage() {
  return (
    <div className="space-y-4">
      {/* Greeting */}
      <div>
        <h1 className="text-2xl font-display font-bold text-white">
          Good morning, <span className="gradient-text">{DEMO_USER.displayName.split(" ")[0]}</span> 👋
        </h1>
        <p className="text-slate-400 text-sm mt-1">
          {new Date().toLocaleDateString("en-IN", { weekday: "long", day: "numeric", month: "long", year: "numeric" })}
          {" · "}Your AI agents have been working for you overnight.
        </p>
      </div>

      {/* AI Briefing - full width */}
      <div className="grid grid-cols-1">
        <AIBriefingCard />
      </div>

      {/* Stats row */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <QuickStats />
      </div>

      {/* Main grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        <SuccessScoreGauge />
        <TodaysTasks />
        <GoalCards />
        <WeeklyChart />
        <AgentActivityLog />
        <NotificationsWidget />
      </div>
    </div>
  );
}
